### ISSUE TITLE
Add brains to atlas collection

### ISSUE THREAD

**Issue by ebridge2** [neurodata/ndmg#112]
will need masks for different brain matters (white, gray, csf) ffor compcor.

**Comment by gkiar** [comment]
@ebridge2 As you see [here](https://github.com/neurodata/ndmg/blob/master/ndmg/scripts/ndmg_bids#L87) when we download atlases in practice we're already downloading everything within [this directory](http://openconnecto.me/mrdata/share/atlases/), which contains everything. If you're doing something different you should convince me why your thing is better or adopt mine :)
