### ISSUE TITLE
How do I get access to raw mr datasets used with the pipeline?

### ISSUE THREAD

**Issue by wrgr** [neurodata/ndmg#116]
I'm a user who wants to use ndmg (either from pip or from docker bids/ndmg).  Do you have source data available for me to use with the pipeline that's already in a compatible format?  e.g., the KKI dataset?  

@cabishop @j6k4m8 @gkiar

**Comment by gkiar** [comment]
We're currently working on a manuscript entitled "Science in the Cloud: A usecase in MRI Connectomics," (an early draft can be found on [arxiv](https://arxiv.org/abs/1610.08484)) in which we use ndmg as an example for demonstrating both reproducible and extensible science. In this manuscript, we mention how to use the ndmg pipeline on any [BIDS](http://bids.neuroimaging.io) organized dataset, and share the NKI1 dataset in this format on a public s3 bucket, `mrneurodata`.

**Comment by wrgr** [comment]
Cool!  Is this the only available data at this time?  If so, would you be interested in help converting the other datasets to the BIDS format and pushing them to this public bucket?

**Comment by gkiar** [comment]
Any BIDS organized data works with the pipeline, and the pipeline has been integrated with the [OpenfMRI](https://openfmri.org/dataset/) computing stack, so any of their datasets with DWI available will also be compatible. As our goal is explicitly not currently MR data distribution, I am not particularly committed to the idea of organizing or uploading more data than those which we are using internally. BIDS is a very well documented specification so anybody should be able to get their data in that format, enabling plug-and-play use with the pipeline.
Close if you're satisfied?

**Comment by gkiar** [comment]
I misunderstood - we'd like your help formatting data and can give it a home. Let's continue dialog offline. :)

**Comment by wrgr** [comment]
Great!  We'll do this for available datasets and contribute back for others to use.
