### ISSUE TITLE
sic

### ISSUE THREAD

**Issue by jovo** [neurodata/ndmg#125]
:-(

IOErrorTraceback (most recent call last)
<ipython-input-1-efc331743dbc> in <module>()
      3 import numpy as np
      4 get_ipython().magic(u'matplotlib inline')
----> 5 g = nx.read_gpickle('/tmp/small_demo/outputs/graphs/desikan/KKI2009_113_1_DTI_s4_desikan.gpickle')
      6 g = nx.adj_matrix(g).todense()
      7 fig = plt.figure(figsize=(7,7))

/usr/local/lib/python2.7/dist-packages/networkx/readwrite/gpickle.pyc in read_gpickle(path)

/usr/local/lib/python2.7/dist-packages/networkx/utils/decorators.pyc in _open_file(func, *args, **kwargs)
    196         if is_string_like(path):
    197             ext = splitext(path)[1]
--> 198             fobj = _dispatch_dict[ext](path, mode=mode)
    199             close_fobj = True
    200         elif hasattr(path, 'read'):

IOError: [Errno 2] No such file or directory: '/tmp/small_demo/outputs/graphs/desikan/KKI2009_113_1_DTI_s4_desikan.gpickle'

**Comment by gkiar** [comment]
Please provide more information. Did you run upstream cells first? It is
**required** that you run all cells order or down stream files will not
exist, which is what I expect is the problem.

I'm running from the beginning now and will report if I observe the same
result.

**Comment by gkiar** [comment]
https://github.com/neurodata/sic/issues/41
