### ISSUE TITLE
Registration QC

### ISSUE THREAD

**Issue by vikramc1** [neurodata/ndmg#126]
@ebridge2 Could you explain the Hellinger distance plot and the jitter plot with MSE  generated from your qc analyses? After a cursory look it doesn't seem like Hellinger distance is too informative for qc

@gkiar

**Comment by ebridge2** [comment]
The jitter plot essentially it is looking at the actual values used by the KDE for its computation, and looking at them before just combining all slices, more or less (ie, you are looking at the discrete MSEs for each slice, with 1 dot per 4th dimension). This adds that if a particular slice is epic-failing, or if there is a total registration failure for a particular volume, you will see points that are inconsistent with the general trend of the plot and you can more easily pinpoint exactly where that epic fail is occuring, so you can then manually go through the brain to find it. When you say "Hellinger distance plot", which are you referring to? The Hellinger distance is just a statistic to define how similar two distributions are; ie, in this case, the similarity of the distribution shown in the "after" registration kde vs the "before" registration kde.

**Comment by jovo** [comment]
we are satisfied with our QC for now
