### ISSUE TITLE
Image Registration qc figures

### ISSUE THREAD

**Issue by vikramc1** [neurodata/ndmg#128]
Generate image registration qc with the registered brain overlayed on the atlas for all datasets (SWU4, KKI2009, BNU1, HNU1)

**Comment by gkiar** [comment]
example single brain registration fig:

![kki2009_113_1_dti_aligned](https://cloud.githubusercontent.com/assets/7087830/21200022/cf6ac13c-c213-11e6-9851-aaedfd0bd343.png)

**Comment by vikramc1** [comment]
More difficult to asses some brains (see below)

![bnu1_0025915_2_dti_aligned](https://cloud.githubusercontent.com/assets/7087830/21302595/fb619b6a-c56c-11e6-8f5f-1800425de4c3.png)

**Comment by jovo** [comment]
@vikramc1 this is great progress, i'm really excited about your QC package to be integrated into ndmg!
