### ISSUE TITLE
graph qc plotting

### ISSUE THREAD

**Issue by gkiar** [neurodata/ndmg#140]
I am switching the graph statistic plotting to show the series of vertex attributes instead of densities as I believe it makes it easier to compare graphs and studies.

The downside of this is that it makes comparing atlases more difficult. Since previously the way we were computing densities didn't play nicely with plotly's interpolation, I'm going to punt on density plots for now and integrate it once I feel happy with the series plots.

The DoD of this issue is that I have graph QA plotting in ndmg that has a flag for either series or density plotting. :)

**Comment by jovo** [comment]
i think this is done?

**Comment by gkiar** [comment]
yup!
