### ISSUE TITLE
Next steps? Finally got some pediatric resting state image pairs for calibration / testing

### ISSUE THREAD

**Issue by davclark** [neurodata/ndmg#146]
Hi @jovo and @gkiar!

I have some images to work with now (thanks to @mbnebel), which are detailed in 
[RS_subjects_multi_randID.csv.txt](https://github.com/neurodata/ndmg/files/775330/RS_subjects_multi_randID.csv.txt) (ends with .txt because GitHub).

Some columns have potentially interesting data for you. Note that some have two scans on the same day, others after quite a few years. There are not that many that are from the tai chi intervention (which is about 10 weeks apart), unfortunately, though we are actively building up that data set (whether kids are in tai chi isn't represented in the current spreadsheet).

What is a good way to get you those images? And would you prefer just some subset of them (e.g., based on diagnosis, which coil was used, etc.)? There are other variables we could obtain, in particular age, other diagnoses, etc.

And they aren’t in BIDS format, but are in a regular format of their own. Given our own tooling, we use Nifti pair images, so our functionals in particular are a whole bunch of img/hdr pairs. The details:

- raw functional data: `LNIR_DATA$\fmri\RestingState\Kids\rsDdata\<SM>\toolbox\<DOS>\Functionals\<run>\<SM>_rs_*.img/.hdr`
- normalized functional data (some SPM, using EPI to EPI template): `LNIR_DATA$\fmri\RestingState\Kids\rsDdata\<SM>\toolbox\<DOS>\Functionals\<run>\wepia<SM>_rs_*.img/.hdr`
- raw anatomical data: `LNIR_DATA$\fmri\RestingState\Kids\rsDdata\<SM>\toolbox\<DOS>\Anatomical\<SM>_MPRAGE.img/.hdr`

I can do pretty much anything, but am also working hard on other stuff, so wanted to check in with y’all first.

In case you’ve forgotten our intention after our meeting, the goal would be to start with doing some comparison of direct EPI vs. MPRAGE T1 normalization.

**Comment by gkiar** [comment]
Hey @davclark, thanks for patiently waiting for me to get back to you! This data+project sounds fun.

I think either via a hard drive (or S3 or Dropbox) you could give us a subset of the dataset for which the scans were both on the same day, and then we'll process it both from the normalized/aligned state and generate connectomes, and from the raw fmri + anatomical scans. The reason for wanting same day scans is we can feel more confident that the brains should look the same than after 10 years, where it's much harder to know.

To confirm: the EPI atlas used for alignment is in MNI152 space, correct?

It's no problem that you store the images as paired files, as we can combine the `.img` and `.hdr` files prior to processing on our end.

@ebridge2 is the man-in-charge of our fmri processing pipeline, so this will be a great test to see if we're doing smart and effective things regarding our alignment. Either he or I (with his instruction) will process this data and score the results using the discriminability metric I chatted with you about last time we met, and will send you a notebook summarizing the results.

**Comment by davclark** [comment]
Just saw that there's a BranHack channel on pediatrics. We should probably report in [there](https://brainhack.slack.com/messages/pediatrics/).

To answer the above question on our target space / template, I need to ask @mbnebel.

**Comment by mbnebel** [comment]
Long answer about the EPI template we've been using: The tissue priors used to segment and normalize the mean fMRI images from which the EPI template was generated were based on icbm_avg_151_gm.mnc, icbm_avg_151_wm.mnc and icbm_avg_151_csf.mnc. I don't know why 151 subjects were used for these tissue priors when 152 subjects were used for the T1 template, but the EPI.nii we use in SPM appears to be aligned with the avg152T1.nii in FSL.

Also, would it be possible to include an inter-subject displacement metric in the results summary? Basically, we've been concatenating the first smoothed functional volume of each subject along the fourth dimension to create a single image file. We then estimate rigid body realignment parameters on this 4D file for each normalization method. Next, we calculate the sum of the absolute value of the six realignment estimates for each frame (subject) relative to the first frame (a random subject from the sample) after converting the three rotational displacements from degrees to millimeters by assuming a 50-mm radius from the cortex to the center of the head. Alternatively, we could calculate this ourselves if you send us the processed data in addition to the summary.

**Comment by davclark** [comment]
I just heard back from the head of IS that we can use KKI's new hot-rod machine that's got 50TB of SSD storage and scads of compute power (including two Nvidia K80s or something like that). The nice thing about this is that we can directly mount our network share and have easy access to ALL of our data.

Would you be amenable to setting up the pipeline there? I'm happy to help. The folks behind this machine are eager to generate some real-world use, and should be pretty supportive.

**Comment by gkiar** [comment]
@davclark I think we should be able to set it up there without problem - is there a scheduler/is it a cluster or a supercomputer?

@mbnebel Regarding an inter-subject displacement metric; we will estimate connectomes from each brain (using both the raw nifti images, and your epi-aligned images), and then compute the discriminability (basically test-retest reliability with some nice statistical properties) from these connectomes. We can then compare discriminability of the graphs when using your epi alignment strategy vs our naive strategy, and inform what method to use moving forward.

@davclark I've joined the brainhack channel, feel free to @ me in there and I'll respond :)

**Comment by mbnebel** [comment]
@gkiar Regarding my inter-subject displacement request: so we're going with option 2? In option 2, you estimate connectomes using 1) your full pipeline on the raw data and 2) your abbreviated pipeline on our epi-aligned images. Then you give us your discriminability summary (with its nice statistical properties) and your T1-aligned data so we can calculate the inter-subject displacement metric ourselves.

**Comment by gkiar** [comment]
Oh, sorry, I misread your comment initially. If you gave us the detailed full algorithm/code for doing this we'd be happy to implement it and do it ourselves, but we don't have that implemented in our stack, so option 2 would be required, yes.

**Comment by davclark** [comment]
@gkiar I think we'll just have lone access to a single shared-memory system. So, no schdeduler is necessary. If you *want* a scheduler, it can be provided. There was also an interest in supporting docker maybe with RKT, again, could be provided if asked (or maybe singularity).

**Comment by davclark** [comment]
I've got data from our archives for all same-day double-scanned kiddos. I need to anonymize before sharing, and I'm wary of doing much with the pair-file (analyze-like) format, so I'm just going to:

- [ ] Convert all files to single-file nifti
- [ ] Anonymize
- [ ] Organize in our shared folder

Note that I'm also working on how to get access for people not on the KKI network.

**Comment by davclark** [comment]
I've organized things a bit more using the [funk-o-nectivity](https://github.com/KKI-CNIR/funk-o-nectivity) repo (I invited the two NDMG team folks). FWIW, I did some experiments using Dask, and found it to be pretty awesome. Don't know what kinds of issues y'all had with it, but I'd be happy to share what I've learned.

Still no non-KKI subnet access to the shared machine, so let me know when you're ready to go and I can put the data up on box if necessary.

**Comment by davclark** [comment]
So it turns out that I need JHEDs from @gkiar and @ebridge2 so I can add you to the relevant consent form and get the OK to share. I'm not sure why, but we don't have data sharing on consents for the participants with same-day scans (they are all in our adolescent protocol).

If your JHED is different for some reason from your my.jh.edu login, please let me know.
