### ISSUE TITLE
fact (susumu) integration 

### ISSUE THREAD

**Issue by wrgr** [neurodata/ndmg#15]
Assess - would be good to get an engineering estimate.  If it's command-line runnable, much more attractive.

**Comment by gkiar** [comment]
Met with Hangyi, Susumu's post-doc, and learned lots about their implementation!

Short of it: The algorithm takes two binary files containing FA map and eigenvectors for each voxel, respectively, stored in C order as 32-bit floats. It also takes a parameter file.

Engineering estimate would be about a week of focused work, I think, as we'd want to get good eigenvector and FA computations, and then ensure the files are properly stored on disc (endians, etc.) and other QA.

It is commandline runnable, and the parameters file is a plain text file which can be generated easily from our data (or, more likely, we will generate a standard file with a few key lines undergoing string replacement based on our data),

I vote we punt on this for now, but when pressure is off to generate a bulk of graphs, this can be a sprint.

@jovo @willgray

**Comment by jovo** [comment]
Perfect
