### ISSUE TITLE
where could I get that downsampled demo data?

### ISSUE THREAD

**Issue by yarikoptic** [neurodata/ndmg#151]
the one referenced in README, e.g. KKI2009_113_1_DTI_s4.bval ?

**Comment by gkiar** [comment]
Hey @yarikoptic - Thanks for reminding me to update the readme! The demo is now run with the following command:

```
ndmg_demo_dwi
```

So long as your machine has `wget` (and the dependencies, such as FSL installed) then that should work. Alternatively, we have a [Dockerfile](https://hub.docker.com/r/neurodata/ndmg/) which has everything installed.

Close if it works? Thanks!

**Comment by gkiar** [comment]
(Updated the `README.md` in 50f1a0a).
