### ISSUE TITLE
Error on Mac OS

### ISSUE THREAD

**Issue by charlesmalpas** [neurodata/ndmg#153]
Hi all,

I have installed ndmg, but encounter the following error on Mac OS 10.12.5:
`Getting test data...
Archive:  /tmp/small_demo.zip
  inflating: small_demo/desikan.nii.gz  
  inflating: small_demo/KKI2009_113_1_DTI_s4.bval  
  inflating: small_demo/KKI2009_113_1_DTI_s4.bvec  
  inflating: small_demo/KKI2009_113_1_DTI_s4.nii  
  inflating: small_demo/KKI2009_113_1_MPRAGE_s4.nii  
  inflating: small_demo/MNI152_T1_1mm_brain_mask_s4.nii.gz  
  inflating: small_demo/MNI152_T1_1mm_s4.nii.gz  
Creating output directory: /tmp/small_demo/outputs
Creating output temp directory: /tmp/small_demo/outputs/tmp
This pipeline will produce the following derivatives...
DTI volume registered to atlas: /tmp/small_demo/outputs/reg_dti/KKI2009_113_1_DTI_s4_aligned.nii.gz
Diffusion tensors in atlas space: /tmp/small_demo/outputs/tensors/KKI2009_113_1_DTI_s4_tensors.npz
Fiber streamlines in atlas space: /tmp/small_demo/outputs/fibers/KKI2009_113_1_DTI_s4_fibers.npz
Graphs of streamlines downsampled to given labels: /tmp/small_demo/outputs/graphs/desikan/KKI2009_113_1_DTI_s4_desikan.gpickle
Generating gradient table...
B-values shape (17,)
         min 0.000000 
         max 700.000000 
B-vectors shape (17, 3)
         min -0.991788 
         max 1.000000 
None
Aligning volumes...
Executing: eddy_correct /tmp/small_demo/outputs/tmp/KKI2009_113_1_DTI_s4_t1.nii.gz /tmp/small_demo/outputs/tmp/KKI2009_113_1_DTI_s4_t1_t2.nii.gz 16
Traceback (most recent call last):
  File "/Users/charlesmalpas/anaconda/bin/ndmg_pipeline", line 11, in <module>
    sys.exit(main())
  File "/Users/charlesmalpas/anaconda/lib/python3.6/site-packages/ndmg/scripts/ndmg_pipeline.py", line 163, in main
    result.clean, result.fmt)
  File "/Users/charlesmalpas/anaconda/lib/python3.6/site-packages/ndmg/scripts/ndmg_pipeline.py", line 90, in ndmg_pipeline
    mgr().dti2atlas(dti1, gtab, mprage, atlas, aligned_dti, outdir, clean)
  File "/Users/charlesmalpas/anaconda/lib/python3.6/site-packages/ndmg/register/register.py", line 162, in dti2atlas
    dti_im = nb.load(dti2)
  File "/Users/charlesmalpas/anaconda/lib/python3.6/site-packages/nibabel/loadsave.py", line 40, in load
    raise FileNotFoundError("No such file: '%s'" % filename)
FileNotFoundError: No such file: '/tmp/small_demo/outputs/tmp/KKI2009_113_1_DTI_s4_t1_t2.nii.gz'`

Any help would be greatly appreciated!

Charles

**Comment by gkiar** [comment]
Hi @charlesmalpas - thanks for installing!

Currently, we've only robustly tested ndmg with Python2.7 (and having installed FSL with Python2.7 as well), and I notice you're using Python3, so I suspect that may be the source of our problem. So long as you're happy using Docker, we *do* have a solution, though!

To run the demo using Docker, you can do the following:

```
### For participant-level analysis
docker run -ti -v /tmp/small_demo:/tmp/small_demo neurodata/ndmg ndmg_demo-dwi

### For group-level analysis
docker run -ti -v /tmp/small_demo:/tmp/small_demo neurodata/ndmg ndmg_demo-qc

### To open the plot in your default viewer (if it didn't open automagically)
open /tmp/small_demo/outputs/qa/desikan/plot.html
```

**Comment by charlesmalpas** [comment]
Thanks, I have reverted to python 2.7 and all works fine! 

Btw, awesome talk today at OHBM! I look forward to playing around with ndmg.

**Comment by gkiar** [comment]
Thanks!! :D
