### ISSUE TITLE
run all available data

### ISSUE THREAD

**Issue by willgray** [neurodata/ndmg#16]

**Comment by gkiar** [comment]
- [ ] KKI2009
- [ ] MRN114
- [ ] NKI24
- [ ] NKI-ENH
- [ ] Jung2015
- [ ] MRN1313
- [ ] ICBM
- [ ] BNU1
- [ ] BNU3
- [ ] MGH-USC
- [ ] 4RTNI
- [ ] SWU4

**Comment by willgray** [comment]
It's my belief now that we can run the remaining subjects this week?  Let's do that and explain why not if some of the datasets are not able to be obtained.  DoD here is at least one graph for each scan.

**Comment by gkiar** [comment]
We discussed, and I am done for now. Open values are those from the LONI IDA which we are unsure we are able to process and distribute.

[data lives here](http://docs.neurodata.io/nddocs/mrgraphs/processed_data.html)

**Comment by willgray** [comment]
so amazing!!!
