### ISSUE TITLE
fp.close() raises "Input/output error" when saving fibers

### ISSUE THREAD

**Issue by araikes** [neurodata/ndmg#161]
Hi all,
I was testing ndmg out on a test participant of ours, having converted to a BIDS-compliant format. I'm running it using docker and am running into a VTK error. I tried to create an error log but was unsuccessful in using the flag correctly, apparently. Pasted below is the output I received. Please advise if there is a way to deal with this particular issue.

Thanks

> PS C:\Users\adamraikes\Desktop\tmp2> docker run -ti -v ${PWD}:/data bids/ndmg /data/ /data/ndmg_outputs participant --log
T1 file: /data/sub-104/ses-01/anat/sub-104_ses-01_run-01_T1w.nii
DWI file: /data/sub-104/ses-01/dwi/sub-104_ses-01_dwi.nii
Bval file: /data/sub-104/ses-01/dwi/sub-104_ses-01_dwi.bval
Bvec file: /data/sub-104/ses-01/dwi/sub-104_ses-01_dwi.bvec
This pipeline will produce the following derivatives...
DWI volume registered to atlas: /data/ndmg_outputs/reg/dwi/sub-104_ses-01_dwi_aligned.nii.gz
Diffusion tensors in atlas space: /data/ndmg_outputs/tensors/sub-104_ses-01_dwi_tensors.npz
Fiber streamlines in atlas space: /data/ndmg_outputs/fibers/sub-104_ses-01_dwi_fibers.npz
Graphs of streamlines downsampled to given labels: /data/ndmg_outputs/graphs/AAL/sub-104_ses-01_dwi_AAL.edgelist, /data/ndmg_outputs/graphs/desikan/sub-104_ses-01_dwi_desikan.edgelist, /data/ndmg_outputs/graphs/Desikan2012/sub-104_ses-01_dwi_Desikan2012.edgelist, /data/ndmg_outputs/graphs/HarvardOxford/sub-104_ses-01_dwi_HarvardOxford.edgelist, /data/ndmg_outputs/graphs/CPAC200/sub-104_ses-01_dwi_CPAC200.edgelist, /data/ndmg_outputs/graphs/Talairach/sub-104_ses-01_dwi_Talairach.edgelist, /data/ndmg_outputs/graphs/JHU/sub-104_ses-01_dwi_JHU.edgelist, /data/ndmg_outputs/graphs/slab907/sub-104_ses-01_dwi_slab907.edgelist, /data/ndmg_outputs/graphs/slab1068/sub-104_ses-01_dwi_slab1068.edgelist, /data/ndmg_outputs/graphs/DS00071/sub-104_ses-01_dwi_DS00071.edgelist, /data/ndmg_outputs/graphs/DS00096/sub-104_ses-01_dwi_DS00096.edgelist, /data/ndmg_outputs/graphs/DS00108/sub-104_ses-01_dwi_DS00108.edgelist, /data/ndmg_outputs/graphs/DS00140/sub-104_ses-01_dwi_DS00140.edgelist, /data/ndmg_outputs/graphs/DS00195/sub-104_ses-01_dwi_DS00195.edgelist, /data/ndmg_outputs/graphs/DS00278/sub-104_ses-01_dwi_DS00278.edgelist, /data/ndmg_outputs/graphs/DS00350/sub-104_ses-01_dwi_DS00350.edgelist, /data/ndmg_outputs/graphs/DS00446/sub-104_ses-01_dwi_DS00446.edgelist, /data/ndmg_outputs/graphs/DS00583/sub-104_ses-01_dwi_DS00583.edgelist, /data/ndmg_outputs/graphs/DS00833/sub-104_ses-01_dwi_DS00833.edgelist, /data/ndmg_outputs/graphs/DS01216/sub-104_ses-01_dwi_DS01216.edgelist, /data/ndmg_outputs/graphs/DS01876/sub-104_ses-01_dwi_DS01876.edgelist, /data/ndmg_outputs/graphs/DS03231/sub-104_ses-01_dwi_DS03231.edgelist, /data/ndmg_outputs/graphs/DS06481/sub-104_ses-01_dwi_DS06481.edgelist, /data/ndmg_outputs/graphs/DS16784/sub-104_ses-01_dwi_DS16784.edgelist, /data/ndmg_outputs/graphs/DS72784/sub-104_ses-01_dwi_DS72784.edgelist
Generating gradient table...
B-values shape (78,)
         min 0.000000
         max 1000.000000
B-vectors shape (78, 3)
         min -0.990377
         max 0.999772
None
Aligning volumes...
Executing: eddy_correct /data/ndmg_outputs/tmp/sub-104_ses-01_dwi_t1.nii.gz /data/ndmg_outputs/tmp/sub-104_ses-01_dwi_t1_t2.nii.gz 0
Executing: epi_reg --epi=/data/ndmg_outputs/tmp/sub-104_ses-01_dwi_t1_t2.nii.gz --t1=/data/sub-104/ses-01/anat/sub-104_ses-01_run-01_T1w.nii --t1brain=/data/ndmg_outputs/tmp/sub-104_ses-01_run-01_T1w_ss.nii.gz --out=/data/ndmg_outputs/tmp/sub-104_ses-01_dwi_t1_ta.nii.gz
Executing: flirt -in /data/sub-104/ses-01/anat/sub-104_ses-01_run-01_T1w.nii -ref /ndmg_atlases/atlas/MNI152_T1_1mm.nii.gz -omat /data/ndmg_outputs/tmp/sub-104_ses-01_run-01_T1w_MNI152_T1_1mm_xfm.mat -dof 12 -bins 256 -cost mutualinfo -searchrx -180 180 -searchry -180 180 -searchrz -180 180
Executing: flirt -in /data/ndmg_outputs/tmp/sub-104_ses-01_dwi_t1_ta.nii.gz -ref /ndmg_atlases/atlas/MNI152_T1_1mm.nii.gz -out /data/ndmg_outputs/tmp/sub-104_ses-01_dwi_t1_ta2.nii.gz -init /data/ndmg_outputs/tmp/sub-104_ses-01_run-01_T1w_MNI152_T1_1mm_xfm.mat -interp trilinear -applyxfm
Cleaning temporary registration files...
Beginning tractography...
Fiber QA failed - VTK for Python not configured properly.
Traceback (most recent call last):
  File "/usr/local/bin/ndmg_bids", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ndmg/scripts/ndmg_bids.py", line 268, in main
    session_level(inDir, outDir, subj, sesh, debug)
  File "/usr/local/lib/python2.7/dist-packages/ndmg/scripts/ndmg_bids.py", line 129, in session_level
    atlas_mask, labels, outDir, clean=(not debug))
  File "/usr/local/lib/python2.7/dist-packages/ndmg/scripts/ndmg_dwi_pipeline.py", line 107, in ndmg_dwi_pipeline
    np.savez(fibers, tracks)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 533, in savez
    _savez(file, args, kwds, False)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 603, in _savez
    zip.close()
  File "/usr/lib/python2.7/zipfile.py", line 1354, in close
    fp.close()
IOError: [Errno 5] Input/output error

**Comment by gkiar** [comment]
Hi @araikes - thanks for reaching out! It appears that the issue is after the VTK portion, as that fails gracefully, but the real error is in the `np.savez(fibers,tracks)` line -- the `zip` library is returning an I/O error.

Based on some digging around, I think there may be a few possible problems... Based on [this issue](https://github.com/log2timeline/plaso/issues/1362#issuecomment-323572730), it's possible that your storage device is out of space, or the save location is a volume to which the tool/container doesn't have access? Also, could you let me know what OS you're using (version of Docker, Windows, etc.)

**Comment by araikes** [comment]
Hi @gkiar,

I'm running Windows 10 (16GB RAM, current free HD = 58GB) and Docker 17.06.1-ce (2 cpu, 6.784GB memory).

It appears that all of the other output files were being created just fine, so I do have write access to my output folder.

**Comment by gkiar** [comment]
Hi @araikes, thanks:

1. Have you been able to reproduce this problem? On this machine? On another?
2. What is your RAM limit for Docker on this machine?
3. What version of the `bids/ndmg` container are you using? I know you've specified no version, thus `latest` was pulled, but when did you download that? (You can check versions and their upload dates [here](https://hub.docker.com/r/bids/ndmg/tags/))

Based on [this issue](https://github.com/omab/python-social-auth/issues/716) I suspect that the container may have been dying anyways (i.e. exceed RAM limit, for instance), and threw this on the way down...

I've not been able to reproduce this error on my Mac or Linux machines.

**Comment by araikes** [comment]
Hi @gkiar 

> Have you been able to reproduce this problem? On this machine? On another?

It happens every time on my machine. I will attempt to replicate it on one of our Ubuntu systems and update this.

> What is your RAM limit for Docker on this machine?

Just shy of 10GiB

>What version of the bids/ndmg container are you using? I know you've specified no version, thus latest was pulled, but when did you download that? (You can check versions and their upload dates here)

I pulled it earlier this week and repulled after you asked, just to be certain.

**Comment by gkiar** [comment]
Thanks @araikes  - let me know how it goes.

What version of Windows 10 do you have, and is your Docker using the toolbox or Hyper-V (i.e. new Windows Shell)?

I suspect, if you're using the Hyper-V version available on Windows Professional, there *might* be an incompatibility between the Kernel of Hyper-V and that which was used when building the container (Debian Linux), and some idiosyncrasy of the `zip` library in Python is making this obvious. If you're using the toolbox sitting on top of virtualbox I'm currently at a loss.

**Comment by araikes** [comment]
Hi @gkiar ... sorry this took long. I haven't been able to get this to run on my Windows machine. However, it appeared to run (on a single participant) on our Linux machines. I'm in the process of finishing up QC on our T1s and will be testing out a full ndmg run here shortly.

I've tried looking through documentation as well as the associated manuscript, but I'm not clear on how to use the outputs after ndmg is finished running. I'm new(ish) to imaging and haven't used connectomes at all.

Basic setup is two groups and two points and I'm curious about changes pre- to -post. If you can give me any guidance (even generally) on how to use ndmg's output, I'd certainly appreciate it.  I know Github isn't necessarily the place for it, so if you're able to assist my email is raikes.research@gmail.com. Thanks

**Comment by gkiar** [comment]
Hey @araikes - thanks for the note, I'll send you an email to chat a bit. And hopefully as a result from our emails I can update some documentation to be more useful for others (I am aware of how painfully incomplete it is...) 😄

And I'll keep this open to see if others are experiencing this issue on Windows.
