### ISSUE TITLE
Phase Enconding direction issue 

### ISSUE THREAD

**Issue by JahanikiaSahar** [neurodata/ndmg#162]
Hello,
I am working to implement distortion correction in my MRI analysis for epi data using fmriprep.
Unfortunately, for all my combinations of i, i-, j and j-, I get an error as follows:

raise Exception("None of the discovered fieldmaps has the right "
Exception: None of the discovered fieldmaps has the right phase encoding direction. Possibly a problem with metadata. If not, rerun with '--ignore fieldmaps' to skip distortion correction step.

Any help will be greatly appreciated.

Thank you.

**Comment by ebridge2** [comment]
Hi Jahanikia, with ndmg, we don't use distortion correction, as only a select number of datasets provide the required metadata to include this in analysis (you need some baseline files for adding distortion correction). I would recommend asking Chris over at [fmriprep](https://github.com/poldracklab/fmriprep) for help regarding distortion correction, or just avoiding it entirely (--ignore fieldmaps option you noted in their pipeline). Let us know if you need any help with ndmg. As this question does not have to do with ndmg, I'm going to mark the issue as "closed", but feel free to post follow ups you might have.
