### ISSUE TITLE
ImportError: cannot import name api

### ISSUE THREAD

**Issue by tsuipen** [neurodata/ndmg#165]
Hello,

Given that I would like to process functional data, I have installed the code from github. I was able to install it as per the instructions, and run the quick demo after installing awscli. When trying to run it on a real dataset

ndmg_bids --participant_label sub-P01 --nproc 8 /path/to/data /path/to/output participant func

 I got this error trace

"/ndmg_atlases/func_atlases/label/HarvardOxfordcort-maxprob-thr25_res-2x2x2.nii.gz
(...)
/ndmg_atlases/func_atlases/mask/HarvardOxford_variant-lateral-ventricles-thr25_res-2x2x2_brainmask.nii.gz
Cannot find atlas information; downloading...
Error 1: Traceback (most recent call last):
  File "/usr/local/bin/aws", line 7, in <module>
    from aws.main import main
  File "/usr/local/lib/python2.7/dist-packages/aws/main.py", line 7, in <module>
    from fabric import api as fab
ImportError: cannot import name api"

It looks like it is AWS/Fabric related, so I understand if the answer is "please use the docker version" (if it has the ability to deal with functional datasets, I'll be happy to : ). 

thank you for any help!
Francisco

**Comment by ebridge2** [comment]
Hey Francisco; sounds like you don't have the atlases set up locally; the scripts can only install the atlases if they have permissions to create and write the directory /atlases locally. Try using the docker container neurodata/m3r-release:0.0.5

**Comment by ebridge2** [comment]
Docker container w functional pipeline is neurodata/m3r-release:0.0.5. Try using that. We will debug this issue later this week to investigate

**Comment by tsuipen** [comment]
Thank you for the answer! Happy to give you more details, I just didn't want to clutter the request or take more of your time, if using the docker container was feasible. The OS is Ubuntu 16.04.5, and the python packages are attached. I also had to install "awscli" in order to get the demo to run.

[requirements.txt](https://github.com/neurodata/ndmg/files/2366959/requirements.txt)

**Comment by tsuipen** [comment]
Hi Eric,

Thank you very much for the prompt reply! I did notice that and create both
directories (/atlases and /ndmg_atlases) with appropriate permissions, but
the error still happened. I'll go the Docker route, I just wanted to make
sure I reported in case other people got stuck with a similar issue.

Francisco
