### ISSUE TITLE
Graph Statistics Output

### ISSUE THREAD

**Issue by GaneshArvapalli** [neurodata/ndmg#170]
Can ndmg.graph be manipulated to provide summary statistics in vector format for multiple graphs (such as [NNZ, Deg Seq, etc.])? I would like to save summary statistics from graphs generated in a pickle file if possible.

**Comment by GaneshArvapalli** [comment]
@jovo, do you have any suggestions for implementation?

**Comment by jovo** [comment]
i don't understand your question, you want to convert the output to a different format? from what to what? please be more clear, and @loftusa can help.

**Comment by GaneshArvapalli** [comment]
To clarify, I am trying to generate a "vector" for a graph that really contains several graph statistics as a list. I have multiple graphs and I would like to create a list for each graph that can then be concatenated by rows to make a data matrix. 

It would be helpful if ndmg could generate statistics on a graph and save them in either a .npz or .pkl file. Or if multiple graphs are used as input, a saved data matrix would be nice.

**Comment by jovo** [comment]
@GaneshArvapalli oh, that seems like a function you can easily write?

**Comment by gkiar** [comment]
@GaneshArvapalli @jovo `ndmg_bids` has a `group` function that computes summary statistics (including those you mentioned) and saves them in pickles, as well as plotting the results.

**Comment by GaneshArvapalli** [comment]
I've looked over the code and the group_level function combined with compute_metrics will be very useful for when I'm writing an implementation. I will update once it's been completed. Thank you!
