### ISSUE TITLE
Versions in functional branch are inconsistent

### ISSUE THREAD

**Issue by gkiar** [neurodata/ndmg#174]
The official release of ndmg is `0.1.0`. On dockerhub, the two most recent versions used for m3r release are `0.5` and `0.7`. In the singularity container for the later, `pip show` says `0.2.0`. In the PR #164, versions `0.0.50` and others also appear.

**Comment by ebridge2** [comment]
https://github.com/neurodata/ndmg/commit/fa305cf2e6ecd81d81c2f68b0fcdd0acd6285eaa changed versions to 0.1.1
