### ISSUE TITLE
major issue with diffusion connectomes generated using functional branch

### ISSUE THREAD

**Issue by gkiar** [neurodata/ndmg#175]
The connectomes generated using the diffusion pipeline on the branch in #164 only have edges on the diagonal, which is the only place they're not supposed to have edges. This was not a problem in previous branches.

i.e.
```
69 69 343
80 80 394
52 52 2809
53 53 1276
```

While some of the other reported issues are a nuisance, this is a big problem that needs to be resolved.

**Comment by gkiar** [comment]
Copying @ebridge2's comment from #164:
> deliberately added the diagonals for CEP. It is very easy to remove a
diagonal if you have a graph with one and don't want it. It is very un-easy
(unless you have lots and lots of scales and a lot of compute resources) to
impute a diagonal without fairly rigorous estimation techniques. Ipso
facto, seemed like it was better to include information that people find
relevant (CEP, YP, both of whom are 2 of our biggest users probably as they
use our data on a daily basis, in particular).

You misunderstand, the graphs *only* have diagonal edges, no others.

**Comment by ebridge2** [comment]
https://github.com/neurodata/ndmg/commit/f1ba5f6619cb1318bb7ab4ff5fa5f18b1ec3bb85
