### ISSUE TITLE
parcellation labels for users

### ISSUE THREAD

**Issue by llevitis** [neurodata/ndmg#177]
Hi, 

Are the labels for the parcellations available for users? The link provided here for the Desikan atlas (https://github.com/neurodata/ndmg/blob/903e202be911ca55d91ddb9f5ba6ac2e02c20a8c/docs/faq.md) is broken. 

Thank you!

**Comment by jovo** [comment]
yes, we are working on that, thanks for letting us know.

**Comment by ebridge2** [comment]
The following command, with the [aws cli](https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html) appropriately configured:
```
aws s3 cp s3://mrneurodata/resources/ndmg_atlases.zip
```
will download all the niftis locally. Note that the fMRI pipeline uses 2mm; the dMRI pipeline uses 1mm.

**Comment by llevitis** [comment]
thank you!!

**Comment by ebridge2** [comment]
No problem; note that we are in the process of making a `json` spec public which will include the label, corresponding anatomical/textual name (if available), centers of mass, and some other useful metadata if available. This will probably be in the next two weeks or so; @loftusa or @j1c will follow up.
