### ISSUE TITLE
_edgelist to _adjmat convert util

### ISSUE THREAD

**Issue by jovo** [neurodata/ndmg#182]
for smaller graphs, we might want to do analyses jointly on dMRI and fMRI, 
and it would be somewhat easier if they were both stored in the same format.
so, a utility function that converts weighted edge lists to adjacency matrices would help people with that.

**Comment by ebridge2** [comment]
NB: https://github.com/neurodata/ndmg/blob/merge-dmri-fmri/ndmg/utils/loadGraphs.py already does the heavy lifting (getting the `_adj` into graphs is the hardest part) from there the rest is just using networkx with the respective "nx.write_####" methods, or alternatively, using the line that saves a numpy matrix as a csv from https://github.com/neurodata/ndmg/blob/merge-dmri-fmri/ndmg/graph/graph.py
