### ISSUE TITLE
Indexing Error in reg_dti_pngs 

### ISSUE THREAD

**Issue by NJB44** [neurodata/ndmg#209]
Hello,

In running the dwi pipeline from a 'neurodata/m3r-release:latest' docker container on a BIDS compliant dataset the program consistently crashed at the end of the registration stage. The line from its traceback mentions an index error from too many dimensions in dti_data[:,:,:,loc] (build/bdist.linux-x86_64/egg/ndmg/stats/qa_regdti.py", line 46, in reg_dti_pngs). 

If I'm not mistaken dti_data in that context points to output/dwi/registered/sub-????_dwi_space-MNI152NLin6_res-1x1x1_registered.nii.gz . I took a look at this and the original file in python and found that the nifti seemed to have started out with a 4D shape but to have been converted into a 3D shape at some point in the registration process (possible in the epi_reg step). The code seems to expect a 4D nifti on that line so I am unclear whether that object is supposed to be 4D or if it should be skipping that process. Do you have any suggestions on other things I can try or if there is an alternative docker image which I should be using instead of neurodata/m3r-release:latest? 

Terminal output:
docker run -ti --rm -v /Volumes/Hanson/CEDAR_MRI/Neuroimaging://CEDAR neurodata/m3r-release:latest /CEDAR/BIDS /CEDAR/practice/0202 participant dwi  --participant_label 0202 --debug --nproc 4
This pipeline will produce the following derivatives...
dMRI volumes preprocessed: /CEDAR/practice/0202/dwi/preproc/sub-0202_dwi_preproc.nii.gz
T1w volume preprocessed: /CEDAR/practice/0202/anat/preproc/sub-0202_T1w_preproc_brain.nii.gz
dMRI volume registered to template: /CEDAR/practice/0202/dwi/registered/sub-0202_dwi_space-MNI152NLin6_res-1x1x1_registered.nii.gz
dMRI Tensors: /CEDAR/practice/0202/dwi/tensor/sub-0202_dwi_space-MNI152NLin6_res-1x1x1_tensor.npz
dMRI Fibers: /CEDAR/practice/0202/dwi/fiber/sub-0202_dwi_space-MNI152NLin6_res-1x1x1_fibers.npz
Connectomes downsampled to given labels: /CEDAR/practice/0202/dwi/roi-connectomes/HarvardOxfordcort-maxprob-thr25_res-1x1x1/sub-0202_dwi_HarvardOxfordcort-maxprob-thr25_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/HarvardOxfordsub-maxprob-thr25_res-1x1x1/sub-0202_dwi_HarvardOxfordsub-maxprob-thr25_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/slab1068_res-1x1x1/sub-0202_dwi_slab1068_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/slab907_res-1x1x1/sub-0202_dwi_slab907_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/aal_res-1x1x1/sub-0202_dwi_aal_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/brodmann_res-1x1x1/sub-0202_dwi_brodmann_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/desikan_res-1x1x1/sub-0202_dwi_desikan_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/CPAC200_res-1x1x1/sub-0202_dwi_CPAC200_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/DS00071_res-1x1x1/sub-0202_dwi_DS00071_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/DS00096_res-1x1x1/sub-0202_dwi_DS00096_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/DS00108_res-1x1x1/sub-0202_dwi_DS00108_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/DS00140_res-1x1x1/sub-0202_dwi_DS00140_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/DS00195_res-1x1x1/sub-0202_dwi_DS00195_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/DS00278_res-1x1x1/sub-0202_dwi_DS00278_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/DS00350_res-1x1x1/sub-0202_dwi_DS00350_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/DS00446_res-1x1x1/sub-0202_dwi_DS00446_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/DS00583_res-1x1x1/sub-0202_dwi_DS00583_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/DS00833_res-1x1x1/sub-0202_dwi_DS00833_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/DS01216_res-1x1x1/sub-0202_dwi_DS01216_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/DK_res-1x1x1/sub-0202_dwi_DK_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/JHU_res-1x1x1/sub-0202_dwi_JHU_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/tissue_res-1x1x1/sub-0202_dwi_tissue_res-1x1x1_measure-spatial-ds.csv, /CEDAR/practice/0202/dwi/roi-connectomes/hemispheric_res-1x1x1/sub-0202_dwi_hemispheric_res-1x1x1_measure-spatial-ds.csv
Generating gradient table...
B-values shape (62,)
         min 0.000000 
         max 1000.000000 
B-vectors shape (62, 3)
         min -0.916579 
         max 0.981036 
None
Aligning volumes...
Executing: eddy_correct /CEDAR/practice/0202/tmp/sub-0202/dwi/preproc/sub-0202_dwi_t1.nii.gz /CEDAR/practice/0202/tmp/sub-0202_dwi_t1_t2.nii.gz 0
Executing: bet /CEDAR/BIDS/sub-0202/anat/sub-0202_T1w.nii.gz /CEDAR/practice/0202/tmp/sub-0202_T1w_ss.nii.gz  -B
Executing: epi_reg --epi=/CEDAR/practice/0202/tmp/sub-0202_dwi_t1_t2.nii.gz --t1=/CEDAR/BIDS/sub-0202/anat/sub-0202_T1w.nii.gz --t1brain=/CEDAR/practice/0202/tmp/sub-0202_T1w_ss.nii.gz --out=/CEDAR/practice/0202/tmp/sub-0202_dwi_t1_ta.nii.gz
Executing: flirt -in /CEDAR/BIDS/sub-0202/anat/sub-0202_T1w.nii.gz -ref /ndmg_atlases/atlas/MNI152NLin6_res-1x1x1_T1w.nii.gz -omat /CEDAR/practice/0202/tmp/sub-0202_T1w_MNI152NLin6_res-1x1x1_T1w_xfm.mat -dof 12 -bins 256 -cost mutualinfo -searchrx -180 180 -searchry -180 180 -searchrz -180 180
Executing: flirt -in /CEDAR/practice/0202/tmp/sub-0202_dwi_t1_ta.nii.gz -ref /ndmg_atlases/atlas/MNI152NLin6_res-1x1x1_T1w.nii.gz -out /CEDAR/practice/0202/tmp/sub-0202_dwi_t1_ta2.nii.gz -init /CEDAR/practice/0202/tmp/sub-0202_T1w_MNI152NLin6_res-1x1x1_T1w_xfm.mat -interp trilinear -applyxfm
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/ndmg/scripts/ndmg_dwi_pipeline.py", line 202, in ndmg_dwi_pipeline
    clean, fmt, big)
  File "build/bdist.linux-x86_64/egg/ndmg/scripts/ndmg_dwi_pipeline.py", line 140, in ndmg_dwi_worker
    reg_dti_pngs(aligned_dwi, b0loc, atlas, namer.dirs['qa']['reg_m'])
  File "build/bdist.linux-x86_64/egg/ndmg/stats/qa_regdti.py", line 46, in reg_dti_pngs
    b0_data = dti_data[:,:,:,loc]
IndexError: too many indices for array

Python Dimension Checking:
>>>import nibabel as nib
>>> aligned_dwi = nib.load("/CEDAR/practice/0202/dwi/registered/sub-0202_dwi_space-MNI152NLin6_res-1x1x1_registered.nii.gz")
>>> aligned_dwi.get_data().ndim
3
>>> starting_file= nib.load("/CEDAR/practice/0202/tmp/sub-0202/dwi/preproc/sub-0202_dwi_t1.nii.gz")
>>> starting_file.get_data().ndim
4
>>> eddy_corrected = nib.load("/CEDAR/practice/0202/tmp/sub-0202_dwi_t1_t2.nii.gz")
>>> eddy_corrected.get_data().ndim
4
>>> epi_reg_image = nib.load("/CEDAR/practice/0202/tmp/sub-0202_dwi_t1_ta.nii.gz")
>>> epi_reg_image.get_data().ndim
3

Best,
Nick Buser

**Comment by loftusa** [comment]
Hey Nick!

Readme is currently not super updated (it will be in the next couple months - there is a schedule planned out)

For now, use `neurodata/ndmg_dev:0.1.1`. That should work for you :)
(You can find it here: https://hub.docker.com/r/neurodata/ndmg_dev/tags)

Let me know if you have any questions.
Alex

**Comment by NJB44** [comment]
Hi Alex,

Thanks for the quick reply and the link! I didn't know about that version so it's really helpful!

I don't know whether I should open this as a separate issue but this one seems to crash earlier on for a simpler reason, namely that we don't have session numbers in our data. When I tried running it I received a list index out of range error. 

The Traceback  pointed me to line 166 of the ndmg_bids.py file and it seems like it has 'ses' and the session number hardcoded in, which makes sense why it would throw an error. I could try a quick fix of removing that part and see if it runs fine otherwise.

Here's the code from that:

Traceback (most recent call last):
  File "/usr/local/bin/ndmg_bids", line 11, in <module>
    load_entry_point('ndmg==0.1.1', 'console_scripts', 'ndmg_bids')()
  File "/ndmg/ndmg/scripts/ndmg_bids.py", line 340, in main
    debug, modality, nproc)
  File "/ndmg/ndmg/scripts/ndmg_bids.py", line 166, in session_level
    in zip(dwis, bvals, bvecs, anats)]
IndexError: list index out of range

line 166 in session_level from ndmg_bids.py

 args = [[dw, bval, bvec, anat, atlas, atlas_mask,
                  labels, "%s%s%s%s%s" % (
                      outDir, '/sub', bval.split('sub')[1].split('/')[0], '/ses', bval.split('ses')[1].split('/')[0])]
                 for
                 (dw, bval, bvec, anat)
                 in zip(dwis, bvals, bvecs, anats)]
 

Thanks again!
Nick

**Comment by loftusa** [comment]
Sure -- you might be able to add a check for if there's a session number in your data. Make sure it's `BIDs` - formatted as well, or the pipeline won't work.

**Comment by NJB44** [comment]
The dwi pipeline seems to work for us once that line is edited. I tried both running it in an interactive container and an editable singularity sandbox, as both ran without errors there I'm closing the issue. 

Thanks for your help!
