### ISSUE TITLE
public=True branch fails in s3_get_data

### ISSUE THREAD

**Issue by davclark** [neurodata/ndmg#270]
If you read through the preceding code, you'll see that you are appending to a variable that's not set up yet.

https://github.com/neurodata/ndmg/blob/c995f311c7d845fa78fd86e41a939d42d1156698/ndmg/utils/s3_utils.py#L117

More generally, you're duplicating stuff that you could just let the S3 libraries / command-line utilities handle - and this might break for some users in unexpected ways. For example, I have multiple AWS accounts and select them with the variable AWS_PROFILE. You're overriding that behavior by going straight to default (which may or may not exist for some people!).

But I appreciate it's a hard thing to provide a simplified interface to any of Amazon's Baroque APIs.

**Comment by loftusa** [comment]
Thanks for the catch!

I think this function is in need of a rewrite anyway - I have been annoyed at the code that pulls and pushes s3 data for quite awhile anyway (it could be much more simple, and use `boto3` - in general, I am of the opinion that there's basically no reason to ever use shell commands within code like this unless it's absolutely necessary).

Probably the solution is to just remove the `public` logic entirely, and just use `boto3.client`'s behavior.
