### ISSUE TITLE
Package and push m2g to LONI Pipeline package server

### ISSUE THREAD

**Issue by willgray** [neurodata/ndmg#33]

**Comment by gkiar** [comment]
obe? I don't particularly want to use LONI and don't think we're planning to, moving forward.

**Comment by willgray** [comment]
Up to you guys if it meets your research goals (@jovo) - worth noting that if we did as a single black box, this would reach a community of MR people that's quite large and different than the nipype people, and is minimal maintenance.  The intent here (months ago) was as part of a sw distribution strategy.  

This is different than develop in loni or use loni in our internal environment.

**Comment by jovo** [comment]
i'm in favor, up to greg what is most exciting to him.
or if really exciting for j6/wg, also great :)

everybody passionately manifesting their dreams :)

On Fri, Jul 8, 2016 at 11:05 AM, William Gray <notifications@github.com>
wrote:

> Up to you guys if it meets your research goals (@jovo
> <https://github.com/jovo>) - worth noting that if we did as a single
> black box, this would reach a community of MR people that's quite large and
> different than the nipype people, and is minimal maintenance. The intent
> here (months ago) was as part of a sw distribution strategy.
>
> This is different than develop in loni or use loni in our internal
> environment.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurodata/ndmg/issues/33#issuecomment-231384230>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AACjchmABrbT8OpOgevYzAP24jkgz80Dks5qTmcdgaJpZM4HVIPg>
> .
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>
