### ISSUE TITLE
Missing qa of FAST (intermediate of preprocess step)

### ISSUE THREAD

**Issue by JialinKang** [neurodata/ndmg#335]
jialin will fix this issue

**Comment by JialinKang** [comment]
the function is segmenting brain to wm, gm and csf

**Comment by JialinKang** [comment]
The function of FSL‘s FAST is to segment t1w_brain.nii.gz into three parts (whiter matter, gray matter and CSF). 
For there is lacking a qa visualizing tools in ndmg pipeline, see here: https://github.com/neurodata/ndmg/tree/staging/ndmg/stats

and the qa function is to get three image form different directions, and each direction have three image from different index. then make this 9 image into a 3*3 image.

**Comment by loftusa** [comment]
Oh ok, didn't catch that. Thanks, proceed as normal!
