### ISSUE TITLE
Deliverables (VERY HIGH LEVEL)

### ISSUE THREAD

**Issue by wrgr** [neurodata/ndmg#34]
**This issue captures where we are going, not specific actions for any person or any week**
- [x] 2000+ Brains with at least one graph
- [x] 7000 x 24 atlas graphs 
- [x] Graphs available online
- [x] Graphs in grutedb
- [x] ndmg as a webservice
- [ ] input data (aligned dti) in neurodata
- [ ] derivatives in neurodata
- [ ] mega-analysis

**Comment by jovo** [comment]
@wrgr @gkiar done enough 👍
