### ISSUE TITLE
Report on DTI compatibility with neurodata

### ISSUE THREAD

**Issue by willgray** [neurodata/ndmg#35]
report on dynamic range of aligned dti volumes and their dtype from 2 different datasets

**Comment by gkiar** [comment]
|           |  KKI2009_113_1  |  SWU4_0025800_1   | MRN114_M87111487 | HCP500_111312_95LR |
|---------|-------------------------|-----------------------------|-----------------------------------|-------------------|
| **dtype** |      float32          |   int16      |    int16  | float32  |
| **min val** |      0.0             |    0         |  0    |   13.483448  |
| **max val** |  491172.75    |    4084    |  3649  |    36052.371  |

**Comment by willgray** [comment]
Thanks for this - great information. 

Next, can we try to understand the useful number of bits?  I suspect that storing data in int16 is sufficient for our actual purposes...perhaps this has been overlooked in the acquisition protocol or people are just storing more than they need.  Or maybe some protocols/imaging requires the precision of float? 

I am unsure of the impact of this and the "right way" to normalize if so.  Any thoughts?  I'm exploring the ideas on google.  We could also try via brute force (e.g., normalizing everything to [0,5000] and casting to int16) and observing the result.

@jovo - who would be able to guide us here?

**Comment by willgray** [comment]
Advantages to normalizing would perhaps assist with quality control and standardized processing.  And also make it easier to fit within existing data standard (int16 is supported now and float32 > 1 is not), although extending the data standard if needed seems like a fine option.

**Comment by jovo** [comment]
The raw data is different types?  Milham and Craddock can help

**Comment by willgray** [comment]
Yea, pretty neat to observe how different, right?

@gkiar - can you reach out?

**Comment by gkiar** [comment]
Yup, just sent an email :)

--
Greg Kiar <gkiar07@gmail.com>

**Comment by willgray** [comment]
@gkiar - any progress here?  Basically need to understand if we can cast these data to int16 or something.  If float, we'll need a new neurodata datatype or extension to the existing one, which is designed for [0,1] - I suspect that is overkill.

**Comment by gkiar** [comment]
@willgray @jovo : after talking with the professor of my MRI course, [Dan Herzka](http://www.bme.jhu.edu/people/primary.php?id=856), I've decided on what I think to be a good way forward. He thinks this would be a good plan and is safe to do (i.e. we aren't losing information doing this). Would still love your input.

- MRI images come off the scanner as uint16. They also contain a transform to map them to a float space.
- MRI images intensity is scaled to match the dynamic range of the datatype (i.e. [0, 2^16-1])
- If noisy voxels exist and appear super bright (not uncommon), the value histogram will be misleadingly low.
- Considering the above, Dan and I think this is a good plan: we will normalize our nifti images such that they are all uint16, and scale the dynamic range of the image to be the original images I<sub>0</sub> (i.e. 0th' percentile) to I<sub>95</sub>.

Initially, this will occur after processing and will only be on the dti volumes being uploaded to ndstore. Somewhere else on the stack, I will test the effect of doing this normalization prior to alignment and tensor estimation, and see if this reduces the batch effects with the aim being improving derivatives for mega-analysis.

I have opened subsequent issues for implementing this normalization for upload and for testing with batch effects.

**Comment by willgray** [comment]
For this week, please fill out table for all available datasets so we can make a better decision.  Trying to set up a quick call with CC to get more guidance.

**Comment by willgray** [comment]
Task for this week is to look at histograms of intensities of raw DTI b0.

**Comment by gkiar** [comment]
[see histograms here](https://github.com/neurodata/nddocs/blob/gh-pages/mrgraphs/dataset_variance.ipynb)

**Comment by jovo** [comment]
i do love them!

On Mon, Feb 29, 2016 at 10:08 AM, Greg Kiar <notifications@github.com>
wrote:

> see histograms here
> <https://github.com/neurodata/nddocs/blob/gh-pages/mrgraphs/dataset_variance.ipynb>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndmg/issues/35#issuecomment-190250896>.
>



-- 
the glass is all full:  half water, half air.
neurodata.io

**Comment by willgray** [comment]
thanks!
