### ISSUE TITLE
Non linear registration

### ISSUE THREAD

**Issue by gkiar** [neurodata/ndmg#36]
Investigate FNIRT (or ANTs) for nonlinear MR registration

**Comment by jovo** [comment]
or, better yet, also compare https://github.com/neurodata/ndreg

**Comment by jovo** [comment]
@dmannan and @loftusa consider this. 
first, make note of all the registrations that we perform.
then, get input from @ebridge2 as to which he believes we should replace, and why.
then, try the ones he thinks we should replace, and see how it goes.
