### ISSUE TITLE
graph format

### ISSUE THREAD

**Issue by gkiar** [neurodata/ndmg#37]
finalize spec for attributed edge + json graph format. Once completed, this will split into subsequent tasks which are write reader/writer for this format in R and Python.

**Comment by gkiar** [comment]
originally discussed [here](https://github.com/neurodata/ndgrutedb/issues/215).

**Comment by willgray** [comment]
I'll lead this one.

**Comment by gkiar** [comment]
We (@jovo, @willgray, @icoming, @disa-mhembere, @gkiar) have come to a decision:

We will store graphs using NetworkX's [gpickle](https://networkx.github.io/documentation/latest/reference/generated/networkx.readwrite.gpickle.write_gpickle.html) format.

The reasons being:
- any custom method developed by us would be faster and more compact, but only marginally
- our custom thing would completely unsupported by community, but gpickle is at least supported by networkx
- our custom thing would take time where this is ready and workable now

**Comment by disa-mhembere** [comment]
i think this is an ok resolution
