### ISSUE TITLE
Write a data descriptor paper, correct neuroparc atlas labels, create analysis code for analyzing m2g results.  Datasets used: https://docs.google.com/spreadsheets/d/1Vr4uL6LZ2qtYdMztYYvf7dRJCvf14NG9x7rERJGPGaI/edit?usp=drive_web&ouid=109524036410778138686

### ISSUE THREAD

**Issue by wilttang** [neurodata/ndmg#381]

**Comment by wilttang** [comment]
initial topic/mock abstract:

Understanding the variability in human brain connectivity is essential in improving our understanding of brain function and diseases. To do so, brains are often modelled as connectomes, or brain graphs, by defining regions of the brain as nodes and the strength of connections between regions as edges. These connectomes are built from diffusion magnetic resonance imaging (dMRI), which use the diffusion of water to model potential connections between the brain’s regions. However, while there is an abundance of publicly available dMRI datasets, there is a lack of corresponding connectome datasets. This is due in part to the lack of standardization, as most studies and labs build and run individualized pipelines that make reproducibility and comparison difficult. The complex nature of building a standardizable connector estimation package is complex and requires collaboration of multiple experts. Thus, researchers interested in using the potential connectome data but who lack this expertise or connections are unable to make use of this MRI data. 

However, the development of the M2G python package, from the Johns Hopkins Open Connectome Project as the first end to end dMRI connectome estimation pipeline, provides an opportunity to correct this imbalance. Researchers may currently use it for their own private data; however to streamline the process for analysis we have already processed and published the results of most public dMRI datasets. This massive trove of publicly available connectome data will enable researchers all over the world to augment their brain research with multiple, standardized connectome datasets.

**Comment by wilttang** [comment]
Sprint 1 Goals: Run all new and current dMRI datasets on AWS. Prepare detailed outline.

**Comment by bdpedigo** [comment]
what are all of the datasets you plan to run ?

**Comment by wilttang** [comment]
We are compiling a list now and testing.

**Comment by wilttang** [comment]
Write a data descriptor paper, fix neuroparc atlas labels, create analysis code for analyzing m2g results. 
Datasets used: https://docs.google.com/spreadsheets/d/1Vr4uL6LZ2qtYdMztYYvf7dRJCvf14NG9x7rERJGPGaI/edit?usp=drive_web&ouid=109524036410778138686
