### ISSUE TITLE
Writing a paper

### ISSUE THREAD

**Issue by huzhen965278384** [neurodata/ndmg#382]

**Comment by huzhen965278384** [comment]
In modern society, analyzing the connectivity inside the brain becomes vital for neural scientists. It helps people to understand the cognitive phenotypes and the activity happened inside the brain. A connectome is an abstract mathematical model of brain structure, a coding technology analyzing the interactions among the brain. NeuroData’s MRI Graphs package, also known as NDMG, is a perfect pipeline uses structural and diffusion MRI data to estimate multi-resolution connectomes. This paper provides a comprehensive MRI connectomes dataset using NDMG package. We collect all the MRI image data through the Internet, then preprocess the image to reduce distortions. After registration, reconstruction, tractography, finally get the connectome. The advantages of NDMG pipeline is that it can handle all kinds of various multi-study dataset. If different pipelines are used on different datasets, or the same pipeline is applied across datasets but requires substantial tuning or manual intervention, or is run using different operating systems, it will waste scientists a lot of time. The dataset we presents can perfectly solve this problem.

**Comment by huzhen965278384** [comment]
This sprint1 's goal:
1. Learning web crawler, combining with google search to find new MRI dataset. Cause our goal is to find all the human brain dMRI dataset throughout the Internet, so now we can't give a list name of datasets right now.
2. Writing the Abstract and Background of the Paper, discuss and modify it with my teammates.
3. After finding all the suitable dataset, do the data-preprocessing according to various situations, such as changing the image data format into nii.gz so that we can run it in m2g package.
4. Building the Dockerfile with teammates and start running the datasets in AWS with the help of Ross to get the connectcome result.

**Comment by XueminZhu-Charmaine** [comment]
1. Correct labelings of Neuroparc atlas with Fang Cai, Zhen Hu, Jialin Kang, and Wilson Tang.
Neuroparc Correction Excel Sheets: https://drive.google.com/drive/folders/1m_cxxYcHkEkJoqg4-c2wmW8FUN52Wuti?usp=sharing

**Comment by XueminZhu-Charmaine** [comment]
2. Writing analysis code and do batch analysis on M2G results with Zhen Hu, Fang Cai, Wilson Tang, and Eric.
Here is the DoD:
https://github.com/NeuroDataDesign/M2G_analysis

**Comment by huzhen965278384** [comment]
These semester's deliverables:
1. A Data Descriptor Paper Draft with all the team members in Team MRI and Eric, Ross. https://www.overleaf.com/7229861125bncdyxrwxkkb . In this whole project, I am responsible for Data collection organization and Technical validation code.
2. Neuroparc Correction Excel Sheets with Fang Cai, Xuemin Zhu, Jialin Kang and Wilson Tang. https://drive.google.com/drive/folders/1m_cxxYcHkEkJoqg4-c2wmW8FUN52Wuti?usp=sharing . The specific contribution can be seen in the Neuroparc Corrections.xlsx 
3. Repo with analysis code and batch analysis on M2G results with Eric, Fang Cai, Wilson Tang and Xuemin, https://github.com/NeuroDataDesign/M2G_analysis 
4. Processed and Uploaded Datasets (on s3) with Fang Cai, Jialin Kang and Xuemin Zhu: https://docs.google.com/spreadsheets/d/1Vr4uL6LZ2qtYdMztYYvf7dRJCvf14NG9x7rERJGPGaI/edit?usp=drive_web&ouid=109524036410778138686
