### ISSUE TITLE
Write a paper

### ISSUE THREAD

**Issue by XueminZhu-Charmaine** [neurodata/ndmg#383]
Trying to write a data descriptor paper about m2g.

**Comment by XueminZhu-Charmaine** [comment]
Abstract
Connectome maps brain network’s elements and connections to create a comprehensive architectural description of the network architecture. M2G pipeline is designed to estimate connectomes using several functional and diffusion studies, which preserves biological variability and reliability. This paper provides a comprehensive dataset of connectome outcomes generating from all available dMRI databases using M2G. The data provide materials and a test bed for neuroscience research.

**Comment by XueminZhu-Charmaine** [comment]
Sprint 1 goals:
1. Run and store all current and new dMRI datasets on AWS
2. Write formal full outline for paper

**Comment by bdpedigo** [comment]
Hi @XueminZhu-Charmaine , can you list what datasets you are planning on running?

**Comment by XueminZhu-Charmaine** [comment]
> Hi @XueminZhu-Charmaine , can you list what datasets you are planning on running?

We're still finding the datasets.

**Comment by XueminZhu-Charmaine** [comment]
1.Correct labelings of Neuroparc atlas with Fang Cai, Zhen Hu, Jialin Kang, and Wilson Tang.
Neuroparc Correction Excel Sheets: https://drive.google.com/drive/folders/1m_cxxYcHkEkJoqg4-c2wmW8FUN52Wuti?usp=sharing

**Comment by XueminZhu-Charmaine** [comment]
2.Writing analysis code and do batch analysis on M2G results with Zhen Hu, Fang Cai, Wilson Tang, and Eric.
Here is the DoD:
https://github.com/NeuroDataDesign/M2G_analysis

**Comment by XueminZhu-Charmaine** [comment]
3. Processed and uploaded datasets on S3 with Fang Cai, Zhen Hu, and Jialin Kang
Here is the DoD:
https://docs.google.com/spreadsheets/d/1Vr4uL6LZ2qtYdMztYYvf7dRJCvf14NG9x7rERJGPGaI/edit?usp=drive_web&ouid=109524036410778138686

**Comment by XueminZhu-Charmaine** [comment]
4.Everyone: Data Descriptor Paper Draft.
Here is the link:
https://www.overleaf.com/7229861125bncdyxrwxkkb
