### ISSUE TITLE
Write a Data Descriptors Paper

### ISSUE THREAD

**Issue by JialinKang** [neurodata/ndmg#384]

**Comment by JialinKang** [comment]
# Abstract:
Connectomes shows the connection of various parts of the brain and plays an important role in medical diagnosis. However, the current dataset of connectomes is very small and there is no uniform standard. So it is important to build a dataset of connectomes that can be used for research.
Our work consists of the following sections: **First**, collecting the MRI nifity data from the Internet. **Second**, preprocessing the data and then generating the connectomes by running the pipeline neurodata/m2g in AWS. **Third**, analyzing the connectomes to build a dataset of connectomes with test people information and demonstrating how to use connectomes in some potential applications. **Last**, comparing this dataset with other common connectomes datasets.

**Comment by JialinKang** [comment]
## Sprint 1 Goals:
Prepare MRI dataset([example](https://neurodata.io/mri/)); run dataset locally via [m2g](https://github.com/neurodata/m2g); create docker image in AWS and run all of the data to produce [connectomes dataset](https://neurodata.io/project/connectomes/). Anlysis the connectomes dataset.
## Sprint 2 Goals:
Finish the [data descriptors paper](https://www.nature.com/sdata/publish/for-authors#aims-scope) works.
Our team paper plan.[link](https://docs.google.com/document/d/1IQH7gAaa-7RKnKwMWoVYKCqiLPZGkEpi_ji0UH6-3Hg/edit)

**Comment by bdpedigo** [comment]
Hi @JialinKang 

As i mentioned in class, I still don't know what datasets you will be running, and what analysis of the connectome datasets means. Also need to specify what the output from "run all of the data" is - is it just graphs? Or are there any other figures you will make?
