### ISSUE TITLE
writing a paper about our connectomes dataset

### ISSUE THREAD

**Issue by luochuankai-JHU** [neurodata/ndmg#385]

**Comment by luochuankai-JHU** [comment]
as the demand of _Scientific Data_

this paper should be composed of:

Title (110 characters maximum, including whitespaces)
Abstract (170 words maximum, no references)
Background & Summary (700 words maximum)
Methods (unlimited length)
Data Records (unlimited length)
Technical Validation (unlimited length)
Usage Notes (unlimited length)
Code Availability
References
Figures (generally no more than three per manuscript)
Tables (generally no more than ten per manuscript)

**Comment by luochuankai-JHU** [comment]
Abstract:

Connectomes in human brain is very complex but it is the fundamental of doing advance research in cognitive science, treatment of brain diseases and brain-computer interface. Right now, most of the open source datasets are original dMRI files which need researchers to do a complicated further processing by themselves to get the connectomes. In this way, we search xxxx different datasets and use the stat-of-the-art pipeline called m2g to generate the world’s biggest human brain connectomes datasets, which contains xxxx samples. Researchers from every fields can directly use our high-level datasets to do your advance analysis about the human brain.

**Comment by luochuankai-JHU** [comment]
Abstract:


Connectomes in human brain is very complex but it is the fundamental of doing advance research in cognitive science, finding treatments of brain diseases and brain-computer interface. Right now, most of the open source datasets are original dMRI files which need researchers to do a complicated further processing by themselves to get the connectomes. In this way, we search xxxx different datasets and use the stat-of-the-art pipeline called m2g to generate the world’s biggest human brain connectomes datasets, which contains xxxx samples and have been checked by clinical biomarkers. Researchers from every fields can directly use our high-level datasets to do your advance analysis about the human brain.

**Comment by luochuankai-JHU** [comment]
Sprint 1 Goals:  run m2g in all open source dMRI datasets and get the connectomes dataset. Write the outline of our paper

**Comment by luochuankai-JHU** [comment]
Sprint 1 Goals: run m2g in all open source dMRI datasets and get the connectomes dataset. Write the draft of our paper.

**Comment by bdpedigo** [comment]
- need more details about what datasets will be run
- need to define what it means for the draft of the paper to be done
- I am guessing the paper will take longer than this to write

**Comment by luochuankai-JHU** [comment]
Sprint 1 Goals:
write the draft of the Title, Abstract, Background & Summary, Methods, Data Records, Usage Notes, Code Availability


run all of the dataset that we have (will have a list after searching) and gererate the connectomes.
