### ISSUE TITLE
Write a paper of data description

### ISSUE THREAD

**Issue by FangCai-fifi** [neurodata/ndmg#386]

**Comment by FangCai-fifi** [comment]
Brain connectomes (Projectomes) are large-scale mappings between regions of the brain to estimate their strengths of connections, created from individual dMRI brain data. M2G is a reliable and scalable tool for MR data analysis, generating summary statistics, QA, and the projectomes. This paper will use M2G to provide a large scale of projectomes generating from all the available dMRI datasets. Statistical results and conclusions will also be included.

**Comment by bdpedigo** [comment]
Hi @FangCai-fifi , can you update with more specifics about what will be done by sprint 1 end? And make sure these are specifics we can evaluate you on

**Comment by FangCai-fifi** [comment]
1. Build a dataset of brain connectomes by finding all available open datasets of dMRI and running them in the m2g pipeline. (Sprint 1)
2. Analysis of those brain connectomes.(Sprint2)
3. Paper.(Sprint2)

**Comment by FangCai-fifi** [comment]
For this semester's deliverables, I have: written a data descriptor paper, created a m2g data website, a repo with analysis code and batch analysis on M2G results w/ Eric, processed and Uploaded Datasets on s3 bucket, and helped with neuroparc correction.
For details:
1. Everyone: Data Descriptor Paper Draft - https://www.overleaf.com/7229861125bncdyxrwxkkb
2. Fang, Hu Zhen, Xuemin, Jialin, Wilson: 
Neuroparc Correction Excel Sheets: https://drive.google.com/drive/folders/1m_cxxYcHkEkJoqg4-c2wmW8FUN52Wuti?usp=sharing
3. Chuankai, Fang:
Website for Data: https://m2g-data-web.readthedocs.io/en/gh-pages 
4. Zhen, Fang, Wilson, Xuemin:
Repo with analysis code and batch analysis on M2G results w/ Eric: https://github.com/NeuroDataDesign/M2G_analysis 
5. Fang, Zhen, Jialin, Xuemin
Processed and Uploaded Datasets (on s3):
https://docs.google.com/spreadsheets/d/1Vr4uL6LZ2qtYdMztYYvf7dRJCvf14NG9x7rERJGPGaI/edit?usp=drive_web&ouid=109524036410778138686
