### ISSUE TITLE
clarify differences between migraine & m2g

### ISSUE THREAD

**Issue by jovo** [neurodata/ndmg#46]
for sephira data, we found signal with migraine, but not m2g.
insofar as we want to figure out why,
i'd like to understand the differences.
can you document it somewhere public, and send me link?
of note, this does not take priority over the weekly priority :)

@willgray

**Comment by gkiar** [comment]
I know little about the migraine architecture (exactly what functions in
JIST, etc.), but so long as @willgray is able to be a reference this
shouldn't be a problem. :)

--
Greg Kiar <gkiar07@gmail.com>

On Wed, Feb 10, 2016 at 6:50 AM, joshua vogelstein <notifications@github.com

**Comment by willgray** [comment]
setup a table with four columns (mrcap, migraine, m2g, ndmg) and rows for each processing method, and we'll work on this together.
