### ISSUE TITLE
quality control

### ISSUE THREAD

**Issue by jovo** [neurodata/ndmg#49]
this issue documents the QC checks that cep is doing that we could implement after running ndmg on a dataset.:

- [x] nnz per graph
- [x] average edge weight (given non-zero weight) per graph

@gkiar @willgray

**Comment by willgray** [comment]
this is all post finishing our graph run, yah?  QA is in the stack.  We will add to the list.  If you want sooner, just let us know.

**Comment by jovo** [comment]
right, finish graphs first.

On Sun, Feb 14, 2016 at 9:07 PM, William Gray <notifications@github.com>
wrote:

> this is all post finishing our graph run, yah? QA is in the stack. We will
> add to the list. If you want sooner, just let us know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndmg/issues/49#issuecomment-184025313>.
>



-- 
the glass is all full:  half water, half air.
neurodata.io

**Comment by willgray** [comment]
If we do stats in ndmg, we should include the R dependency as an optional thing so that people don't have to have it.  We do this in ndio frequently for things like libtiff.

I'm open to being convinced otherwise.

**Comment by jovo** [comment]
i support.
i'd expect a set of QC scripts, not sure where they would live,
perhaps distributed (some in reliability repo, some in FlashR, etc.)

On Tue, Feb 16, 2016 at 9:56 AM, William Gray <notifications@github.com>
wrote:

> If we do stats in ndmg, we should include the R dependency as an optional
> thing so that people don't have to have it. We do this in ndio frequently
> for things like libtiff.
>
> I'm open to being convinced otherwise.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndmg/issues/49#issuecomment-184714889>.
>



-- 
the glass is all full:  half water, half air.
neurodata.io

**Comment by willgray** [comment]
Let's try to get to this as a second tier priority this week - getting a bit stale.

**Comment by gkiar** [comment]
This now exists [here](https://github.com/neurodata/dataset_variance/blob/master/code/experiment/compute_metrics.py). 😄
