### ISSUE TITLE
multiscale graphs

### ISSUE THREAD

**Issue by jovo** [neurodata/ndmg#50]
please point @shangsiwang to a folder with TRT data including all ~24 different atlases, 
and tell him the number of ROIs per atlas.

@willgray

**Comment by willgray** [comment]
did this happen?  I didn't see the email.  @gkiar

**Comment by gkiar** [comment]
We hadn't yet generated multigraphs on all datasets with ndmg, so I am working on getting the data before I send this email. It will be done this week.

**Comment by willgray** [comment]
great thanks!

**Comment by gkiar** [comment]
I emailed this data and put a public link [here](http://docs.neurodata.io/nddocs/mrgraphs/processed_data.html).

**Comment by jovo** [comment]
@willgray - closed right? re-open if not.
