### ISSUE TITLE
architecture diagram of ndmg

### ISSUE THREAD

**Issue by willgray** [neurodata/ndmg#53]
we did this as a concept lucidchart.  Let's update it and clarify what goes in each box. 

assigning to @gkiar but joint effort with @willgray

**Comment by gkiar** [comment]
First pass:
![ndmg architecture](https://cloud.githubusercontent.com/assets/4883288/13099940/c058e51c-d505-11e5-83c3-75164afa59a1.png)

@willgray I've shared you an editable link on slack. Once this is done, I'll add it to the nddocs page.

**Comment by willgray** [comment]
I made minor changes - think this looks amazing.  Feel free to close again once on the docs page.

**Comment by willgray** [comment]
I see...it's there already!  My changes are so minor not worth it - we can pull them in next go around.
