### ISSUE TITLE
write data converters for networkx -> graphml

### ISSUE THREAD

**Issue by wrgr** [neurodata/ndmg#67]

**Comment by willgray** [comment]
just saw this - we discovered awhile back that you could just use the networkx built-ins for this.  Works lovely for me.  If we add, would be an optional arg to graphs that allowed for writing out as networkx or graphml (and perhaps numpy), and <5 lines of code.  I'll get there by end of summer if not done earlier:  

https://networkx.github.io/documentation/networkx-1.10/reference/readwrite.graphml.html

**Comment by gkiar** [comment]
We already have a flag in the pipeline enabling writing in either of these formats, and I've made a converter going from networkx to graphml.
