### ISSUE TITLE
Move raw data to somewhere public

### ISSUE THREAD

**Issue by gkiar** [neurodata/ndmg#68]
Currently all raw data used for processing in ndmg lives on brainstore. From bc1, this can be accessed at:

/brainstore/MR/data/{datasetname}/raw/

The public directory we host the graphs at is also on brainstore, and similarly can be accessed at:

/brainstore/mrocp/data/share/dti/{datasetname}/...

Move them at your leisure :)

@MrAE @jovo

**Comment by jovo** [comment]
@loftusa i doubt the raw data is still there, @falkben would know.
but we should keep track of where the raw data are. 
i believe m2g.io does do that for all the public processed data. 

we don't really have private data right now, so we don't need to worry about that for now,

**Comment by jovo** [comment]
@falkben would it be useful for @loftusa to make a list of all the data in that bucket? 
(since apparently not all of it is available through that website?
