### ISSUE TITLE
assess dipy tensor estimation options

### ISSUE THREAD

**Issue by wrgr** [neurodata/ndmg#7]
Goal is to choose something that seems robust with reasonable parameters.

**Comment by jovo** [comment]
i am satisfied if discriminability (which is what we called reliability) is
high.
to compare multiple different pipelines with the same discriminability,
i suggest comparing discriminability on subgraphs

On Wed, Feb 3, 2016 at 3:03 AM, William Gray <notifications@github.com>
wrote:

> Goal is to choose something that seems robust with reasonable parameters.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/ndmg/issues/7>.
>



-- 
the glass is all full:  half water, half air.
neurodata.io
