### ISSUE TITLE
Raise an exception if the subprocess fails

### ISSUE THREAD

**Issue by j6k4m8** [neurodata/ndmg#71]
Right now, running `ndmg_pipeline.py` can fail silently on one step, and the only indication that something went wrong is when the *following* step cannot find the produced file.

For example, if `eddy_correct` fails, then you don't know until the following `register` `dti2atlas` step cannot find the temp `*t1_t2` file.

To resolve, change [`Popen`s](https://github.com/neurodata/ndmg/blob/master/ndmg/register/register.py#L82) to [`subprocess.check_output`](https://github.com/j6k4m8/pyrastitcher/blob/master/pyrastitcher/__init__.py#L83), which returns the stdout of the CLI executable.

(Currently looking into PR'ing this in the next few days, though I'd love to be beaten to the punch!)

cc @willgray

**Comment by gkiar** [comment]
This can actually be done with Popen just as easily using `communicate` and `returncode`. I'm cleaning up/modularizing code atm and have added this check. You'll see the commit tagging this issue momentarily.
