### ISSUE TITLE
ndmg assumes that ndmg is installed

### ISSUE THREAD

**Issue by j6k4m8** [neurodata/ndmg#72]
## Steps to reproduce:
- Download ndmg (`git clone https://github.com/neurodata/ndmg`)
- Try running a ndmg script (`ndmg/ndmg/ndmg_pipeline.py`)
## Expected Behavior:

ndmg performs the pipeline as usual.
## Actual Behavior:

ndmg tries to `import ndmg.utils`, but I never pip-installed ndmg, so it fails!! Instead, should import from a relative path so that this works whether or not ndmg was pip-installed, or perhaps if it was installed on a system where ndmg is not installed for all users, and is thus not in the pip cache directory.

**Comment by gkiar** [comment]
As this is a Python **package** it is expected that it is **installed**. I clarified the install instructions in commit https://github.com/neurodata/ndmg/commit/bf5ee08db6a83dd508cdcb82ddf8649005d1cfd7 for those who choose to install via Github and don't know how.

Also, if you did `cd ndmg` prior to running that command (i.e. were in the base directory of the repo) this script would still work without installing. This, however, would require you to have all other dependencies (such as DiPy) already installed.

**Comment by willgray** [comment]
@gkiar - i hear what you are saying, but still might be a nice enhancement.  use cases like no sudo, or permission to install things, or desire to use a library without pip bloat?

**Comment by gkiar** [comment]
And I'm saying it already exists, you just have to cd in 1 further
directory. For example, ndio doesn't work in a parallel example you just
described. It does if you move in 1 directory. There is no problem, just
laziness :)

--
Greg Kiar <gkiar07@gmail.com>

**Comment by gkiar** [comment]
Parallel for ndio. This fails:
```
git clone https://github.com/neurodata/ndio.git
python -c "import ndio"
```

This does not:
```
git clone https://github.com/neurodata/ndio.git
cd ndio
python -c "import ndio"
```

Same applies here.

**Comment by j6k4m8** [comment]
Sorry, I think my initial report was unclear —

I mean that the `ndmg_pipeline.py` script fails (due to being unable to
import `ndmg.utils`) unless ndmg has been installed — I totally agree that
the git/raw filestructure is set up correctly!

I'm not totally sure what the solution to this is, but I imagine using
relative imports between files means that even if you call
`ndmg_pipeline.py` from outside of the ndmg directory, it should still find
the right files.

Relative imports: https://docs.python.org/2.5/whatsnew/pep-328.html

**Comment by gkiar** [comment]
Ah, I see better now what you mean. This has a very low priority on my stack, but feel free to fix on a dev branch and PR. Once it passes Travis, I'll skim the code before merging to master. Otherwise, it'll be a while for me to get to it.

**Comment by j6k4m8** [comment]
Super cool — I'll play around with it!
