### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by jovo** [neurodata/ndmg#73]
@gkiar  - @zheng-da  could try classification on either:

1) dense vectorized registered DTI data + sex (or some other covariates)
2) sparse vectorized big DTI graphs + sex (or some other covariates)

perhaps we already have #2?

when i went [here](http://openconnecto.me/mrdata/share/dti/ndmg_v0011/KKI2009/)

i could not find the voxelwise graphs.

could you point us to one or both said datasets at your earliest convenience?

**Comment by gkiar** [comment]
Because of space and time constraints we never kept (and subsequently stopped generating) big graphs with ndmg. We have older graphs from m2g that are "big" located [here](http://openconnecto.me/data/public/MR/m2g_v1_1_1/KKI2009/derivatives/bg/).

**Comment by ebridge2** [comment]
@gkiar can you point @zheng-da to (1)
@zheng-da you could the above link with those big ones for your sparse thing.

**Comment by jovo** [comment]
(2) is here: http://openconnecto.me/mrdata/share/dti/ndmg_v0011/MRN114/DS72784/

(1) @gkiar will send link to same data

**Comment by gkiar** [comment]
@zheng-da, I've found some documentation for reading nifti1 images in C, which may be the easiest way to get the data into your format, like we chatted about.

The package provided in C by the folks who make and maintain nifti can be [found here](https://nifti.nimh.nih.gov/pub/dist/src/).

There is a ton of stuff, but I think I've found the [example upon which you should base your implementation](https://nifti.nimh.nih.gov/pub/dist/src/nifti/examples/clib_01_read_write.c).

**Comment by gkiar** [comment]
Or, since it was easier, I just read the images and converted them to binary vectors for you. 😄  From awesome you can find them at the same location in the additional subfolder `bins`. These files have no header, and are just vectors of the images in `float32`. Enjoy!

**Comment by jovo** [comment]
thanks @gkiar, you rock!

On Tue, Jul 5, 2016 at 4:50 PM, Greg Kiar <notifications@github.com> wrote:

> Or, since it was easier, I just read the images and converted them to
> binary vectors for you. 😄 From awesome you can find them at the same
> location in the additional subfolder bins. These files have no header,
> and are just vectors of the images in float32. Enjoy!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurodata/ndmg/issues/73#issuecomment-230598948>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AACjcpng6vUbSh53SB3ImMDG8yXOM_-4ks5qSsOPgaJpZM4I5FDk>
> .
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>
