### ISSUE TITLE
QC plots on all graphs for all atlases

### ISSUE THREAD

**Issue by jovo** [neurodata/ndmg#81]
@gkiar you made some beautiful QC plots for various graph attributes.
and we looked at many of the datasets using them, but only 1 scale i think?

shall we look at all datasets & scales using those plots?

**Comment by gkiar** [comment]
We looked at 8 datasets and 3 scales - desikan, cpac200, talairach. If you
want I can make re-running all of this on everything else a priority this
week.

--
Greg Kiar <gkiar07@gmail.com>

**Comment by gkiar** [comment]
Covered in #84
